jobs:
  build-java:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Print Greeting Message
      run: echo "Hi, I am from COSC 1209 class"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Ensure gradlew exists
      run: ls -l gradlew || echo "gradlew not found!"

    - name: Grant execute permission for Gradle (Linux/Mac)
      if: runner.os != 'Windows'
      run: chmod +x gradlew

    - name: Build with Gradle (Linux/Mac)
      if: runner.os != 'Windows'
      run: ./gradlew build
      
    - name: Build with Gradle (Windows)
      if: runner.os == 'Windows'
      run: gradlew.bat build
